In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as splt
import seaborn

In [2]:
df = pd.read_csv('AB.csv')

In [4]:
df
df.dtypes

Power            float64
Va               float64
Vb               float64
Vc               float64
Va_RMS           float64
Vb_RMS           float64
Vc_RMS           float64
Ia               float64
Ib               float64
Ic               float64
Ia_RMS           float64
Ib_RMS           float64
Ic_RMS           float64
Target Output      int64
dtype: object

In [3]:
df.shape
df['Target Output'].value_counts()

1    30043
0     7507
Name: Target Output, dtype: int64

In [5]:
df.isnull().sum()

Power            0
Va               0
Vb               0
Vc               0
Va_RMS           0
Vb_RMS           0
Vc_RMS           0
Ia               0
Ib               0
Ic               0
Ia_RMS           0
Ib_RMS           0
Ic_RMS           0
Target Output    0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [7]:
x = df.drop(['Target Output'],axis=1)

In [13]:
x

,Power,Va,Vb,Vc,Va_RMS,Vb_RMS,Vc_RMS,Ia,Ib,Ic,Ia_RMS,Ib_RMS,Ic_RMS
0,1.333262e+06,-1740.231117,-6036.317048,7776.548165,120.000000,120.000000,120.000000,-37.657558,-70.577899,108.235457,120.000000,120.000000,120.000000
1,1.333262e+06,-1740.231117,-6036.317048,7776.548165,120.000000,120.000000,120.000000,-37.657558,-70.577899,108.235457,120.000000,120.000000,120.000000
2,1.333262e+06,-1740.231117,-6036.317048,7776.548165,120.000000,120.000000,120.000000,-37.657558,-70.577899,108.235457,120.000000,120.000000,120.000000
3,1.333262e+06,-1740.231117,-6036.317048,7776.548165,120.000000,120.000000,120.000000,-37.657558,-70.577899,108.235457,120.000000,120.000000,120.000000
4,1.333262e+06,-1740.231117,-6036.317048,7776.548165,120.000000,120.000000,120.000000,-37.657558,-70.577899,108.235457,120.000000,120.000000,120.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37545,1.349808e+06,-2068.458073,-5977.765782,8046.223745,6312.423869,5462.547866,5917.964790,-40.473343,-67.058862,107.532211,83.083921,72.913726,75.946499
37546,1.349715e+06,-2048.107856,-5992.429459,8040.537204,6311.227798,5461.270423,5920.415674,-40.215975,-67.269467,107.485448,83.075693,72.892401,75.978523
37547,1.349622e+06,-2027.744677,-6007.055309,8034.799875,6310.021637,5460.004420,5922.865238,-39.958371,-67.479630,107.438006,83.067322,72.871195,76.010563
37548,1.349529e+06,-2007.368665,-6021.643240,8029.011794,6308.805412,5458.749897,5925.313421,-39.700531,-67.689350,107.389886,83.058809,72.850110,76.042618
37549,1.349437e+06,-1986.979949,-6036.193160,8023.172997,6307.579148,5457.506892,5927.760165,-39.442458,-67.898625,107.341088,83.050154,72.829144,76.074688

In [8]:
y = df['Target Output']

In [16]:
y

0        1
1        1
2        1
3        1
4        1
        ..
37545    1
37546    1
37547    1
37548    1
37549    1
Name: Target Output, Length: 37550, dtype: int64

In [9]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.25,random_state=1)

In [18]:
xtrain

,Power,Va,Vb,Vc,Va_RMS,Vb_RMS,Vc_RMS,Ia,Ib,Ic,Ia_RMS,Ib_RMS,Ic_RMS
9409,1.061662e+05,-1384.140043,-1383.887506,2768.189472,2917.450780,2916.595228,5834.094842,-107.112317,81.549357,25.562889,374.848625,318.400579,77.653690
27805,1.322696e+06,3452.569211,-8319.458678,4866.889336,5749.356067,5574.774013,6369.292317,31.341859,-103.669565,72.327713,77.082452,72.864369,82.793766
23310,1.316118e+06,8264.197560,-3042.263208,-5221.934492,5798.201462,6358.042592,5538.095439,105.019871,-45.967501,-59.052363,75.618289,83.445371,73.352489
1643,1.360842e+06,-5616.875774,8166.284924,-2549.409151,120.000000,120.000000,120.000000,-64.903190,108.416065,-43.512874,120.000000,120.000000,120.000000
13135,1.106065e+06,7810.032146,-5598.396912,-2211.594125,3599.735393,3728.800921,5903.194063,87.000731,-69.143720,-17.857105,288.979285,216.691006,78.553007
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,4.125300e+05,-2118.113878,-2118.506762,4236.544291,3188.955954,3187.981099,6377.008514,84.165741,-149.075402,64.907946,421.559066,355.627576,83.297979
32511,1.351919e+06,-2632.407523,-5552.281854,8184.689257,6341.723604,5502.767928,5849.051881,-47.757813,-60.808005,108.565825,83.251325,73.610167,75.059388
5192,8.122022e+05,-3077.011775,-3077.440652,6154.516860,6039.298112,5134.441798,6293.636779,96.851740,-184.825537,87.972220,79.822670,75.560235,81.347400
12172,8.939458e+05,-3500.946224,-3500.073781,7001.174309,2700.332689,2699.474247,5399.865289,-334.615125,249.514374,85.099296,334.842869,276.139643,70.951976
33003,1.319781e+06,6590.395686,-7749.887287,1159.491481,5417.367678,6023.887229,6250.438933,75.777184,-101.942263,26.165085,72.151206,77.991633,82.365037

In [10]:
model = SVC()
model.fit(xtrain,ytrain)
model.score(xtest,ytest)

0.9363016616957819

In [31]:
model_c = SVC(C=15)
model_c.fit(xtrain,ytrain)
model_c.score(xtest,ytest)

0.9429058372390285

In [33]:
model_g = SVC(gamma=1)
model_g.fit(xtrain,ytrain)
model_g.score(xtest,ytest)

0.7953770771197273

In [36]:
model_g = SVC(gamma=50)
model_g.fit(xtrain,ytrain)
model_g.score(xtest,ytest)

0.7953770771197273

In [ ]:
model_linear_kernal = SVC(kernel='linear', gamma='auto',C=2)
model_linear_kernal.fit(xtrain,ytrain)

In [ ]:
classifier = svm.SVC()
classifier.fit(xtrain,ytrain)
y_predict = classifier.predict(xtest)